version: "3.1"

services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./database:/var/lib/postgresql/data
